### ISSUE TITLE
Invalid value for parameter source

### ISSUE THREAD

**Issue by kjibran** [erick-otenyo/leaflet-pgrouting-example#1]
Hello,

First of all, thank you so much for your great series of tutorials. I have been playing with pgRouting using them. I was able to follow all steps, and tested Shortest_path and nearest_vertex SQL views in my browser. They worked well. I proceeded to the last step to building routing application using JS.

The code works without errors and I am able to see two draggable markers (source and target) in my browser like this.

![image](https://user-images.githubusercontent.com/6083619/59551594-510c7b80-8f7c-11e9-8454-3488f2f4dc13.png)

However, the shortest_path algorithm doesn't work here, and I can't see the shortest path drawn between two points. I had a look at my GeoServer console log. It says:

![image](https://user-images.githubusercontent.com/6083619/59551633-bceee400-8f7c-11e9-8c8e-b448e7fc8844.png)

So, most likely, the markers are unable to calculate source and target values, and send them to GeoServer? I googled the error, came across this [link](https://stackoverflow.com/questions/17543440/java-sql-sqlexception-invalid-value-for-getint-glomindz-support) which says it might be due to the invalid column type e.g. source in this case.

Can you please help to get through the last step?

I am on Windows 8 (x64 based machine), and using PostgreSQL 10. Let me now if you need any other information.

**Comment by erick-otenyo** [comment]
@kjibran Hi.. Just seeing this. Did you manage to solve the issue ?

**Comment by kjibran** [comment]
Hi, no I couldn't get it to work. Still the same issue :(... I tried on both postgresql 10 (Windows 8) and postgresql 9.5 (Windows 10) with geoserver 2.15.1. Can you please help to resolve the issue?

**Comment by erick-otenyo** [comment]
Can you try to view the developer tools under network after dragging a marker to see the if the correct values are being sent to the Geoserver?

**Comment by kjibran** [comment]
I have been playing with it for quite a while. Before front- end client application, I tested "nearest_vertex" and "shortest_path SQL views in the browser, they work. In the geoserver console log, I can see values of X and Y extracted from map. I think it's source and target initial values "NULL" in JS code, that made geoserver to throw error: invalid value source parameter. The geoserver stucks here and complains "NULL can't match with validation parameters" which is set to integer.

What are your thoughts? A bit later I could provide the full error log but I can see the main problem, as i mentioned above.

By developer tools, you meant to test in browser? I have done that, it works.

**Comment by kjibran** [comment]
Alright, I figured out! Here is what's happening in the developer tools under network (Google Chrome).

When I launch the application via VS Code (Live-Server), the following map appears:

![image](https://user-images.githubusercontent.com/6083619/61323408-37c34d00-a810-11e9-98fd-42fbc5fb3812.png)

and when I go to the "developer tools", the following warning and errors appear:

```
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.

Access to XMLHttpRequest at 'http://localhost:5000/geoserver/wfs?service=WFS&version=1.0.0&request=GetFe…rest_vertex&outputformat=application/json&viewparams=x:16.56772;y:62.71243;' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
send	@	jquery-3.2.0.min.js:4
ajax	@	jquery-3.2.0.min.js:4
getVertex	@	app.js:54
(anonymous)	@	app.js:87

Access to XMLHttpRequest at 'http://localhost:5000/geoserver/wfs?service=WFS&version=1.0.0&request=GetFe…rest_vertex&outputformat=application/json&viewparams=x:16.56992;y:62.71243;' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
send	@	jquery-3.2.0.min.js:4
ajax	@	jquery-3.2.0.min.js:4
getVertex	@	app.js:54
(anonymous)	@	app.js:88

Access to XMLHttpRequest at 'http://localhost:5000/geoserver/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=postgres:shortest_path&outputformat=application/json&viewparams=source:null;target:null;' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

I dragged the left marker slightly up, and more errors appear:

```
jquery-3.2.0.min.js:4 Access to XMLHttpRequest at 'http://localhost:5000/geoserver/wfs?service=WFS&version=1.0.0&request=GetFe…ormat=application/json&viewparams=x:16.56739377975464;y:62.712800518536184;' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
send	@	jquery-3.2.0.min.js:4
ajax	@	jquery-3.2.0.min.js:4
getVertex	@	app.js:54
(anonymous)	@	app.js:33
fire	@	leaflet.js:5
_onDragEnd	@	leaflet.js:9
fire	@	leaflet.js:5
finishDrag	@	leaflet.js:8
_onUp	@	leaflet.js:8
h	@	leaflet.js:6
_handlePointer	@	leaflet.js:8
(anonymous)	@	leaflet.js:8

Access to XMLHttpRequest at 'http://localhost:5000/geoserver/wfs?service=WFS&version=1.0.0&request=GetFeature&typeName=postgres:shortest_path&outputformat=application/json&viewparams=source:null;target:null;' from origin 'http://127.0.0.1:5500' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

Cross-Origin Read Blocking (CORB) blocked cross-origin response http://localhost:5000/geoserver/wfs?service=WFS&version=1.0.0&request=GetFe…test_path&outputformat=application/json&viewparams=source:null;target:null; with MIME type text/xml. See https://www.chromestatus.com/feature/5629709824032768 for more details.
send	@	jquery-3.2.0.min.js:4
ajax	@	jquery-3.2.0.min.js:4
r.<computed>	@	jquery-3.2.0.min.js:4
getJSON	@	jquery-3.2.0.min.js:4
getRoute	@	app.js:80
(anonymous)	@	app.js:34
fire	@	leaflet.js:5
_onDragEnd	@	leaflet.js:9
fire	@	leaflet.js:5
finishDrag	@	leaflet.js:8
_onUp	@	leaflet.js:8
h	@	leaflet.js:6
_handlePointer	@	leaflet.js:8
(anonymous)	@	leaflet.js:8
```
I think the app correctly retrieves the correct values of `lon, lat` but I am not sure if they are being sent to Geoserver or not. Also, `source:NULL` and `target:NULL` appears in error here.

Also, I had a look at `headers` under network. I can't see header `Access-Control-Allow-Origin `in `app.js.`

Hope it gives you some idea. Just to remind you that I am on Windows 10, PostgreSQL 9.5 and GeoServer 2.15.1.

**Comment by erick-otenyo** [comment]
This seems to be an issue with CORS in your Geoserver not enabled. The source and target are null when the shortest path request is made because those variables are supposed to be assigned values once successful nearest vertex requests are made, which in this case are not successful. Which server are you using? Tomcat or Jetty? Just do a quick search on Google on how to enable CORS on geoserver specific to your web server.

**Comment by kjibran** [comment]
Right, I fixed the issue of CORS at Geoserver, and it worked!! Thanks a lot. I am just using the development "Live-Server" via VS Code, not sure which one it is, Jetty or Tomcat. But, I could see "jetty" in geoserver log. Your thoughts?

I am happy to close to issue but I have two questions. I would highly appreciate if you could help.

1) Is it possible to add colors to the markers? for example: source:green and target:red. If yes, how could I do this?

2) How could I add/draw the "line" from the "point of click (on the map)" to the nearest vertex during display of "shortest_path"? Why.. because sometimes there is a significant distance between the point clicked on map and the nearest vertex. I think one of the SQL views (or maybe both) needs to be edited.

**Comment by erick-otenyo** [comment]
> But, I could see "jetty" in geoserver log. Your thoughts?

This is the server that is running Geoserver, and not the Live server that is just running your app

> 1. Is it possible to add colors to the markers? for example: source:green and target:red. If yes, how could I do this?

Yes it is possible. The easiest way is to use different icons for particular markers. You can check an example here https://github.com/pointhi/leaflet-color-markers

> 2. How could I add/draw the "line" from the "point of click (on the map)" to the nearest vertex during display of "shortest_path"? Why.. because sometimes there is a significant distance between the point clicked on map and the nearest vertex. I think one of the SQL views (or maybe both) needs to be edited.

If you mean something like in the screenshot below, I think it is possible. I got this from [here](https://www.liedman.net/leaflet-routing-machine/)
![screenshot-www liedman net-2019 07 17-14_29_27](https://user-images.githubusercontent.com/20169543/61375598-91268d00-a89f-11e9-8ca9-6ce2d7986f55.png)

One way to do this is from the frontend. You can check the first and last points of the returned linestring against the respective markers position, and maybe calculate the distance between them, using for example a library like Turf JS. You can set a minimum distance threshold, and if the distance is longer than this threshold, then you can have a way to extend the returned linestring using for example Turf JS again.

I may update the code to have this feature, but if you can also figure it out, please feel free to do a PR.

**Comment by kjibran** [comment]
Alright, I would give it a try and come back to you. Thanks.
